name: Update EuroMillions data

on:
  workflow_dispatch:
  schedule:
    # Run around draw windows (Tue/Fri EU evenings) every 30 min
    - cron: "*/30 20-23 * * 2,5"
    # Daily backup run (morning UTC)
    - cron: "17 06 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Update EuroMillions data
        run: |
          python scripts/update_euromillions.py --out-dir site

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update EuroMillions history + site"
          file_pattern: |
            euromillions.json
            latest.json
            site/**
